### PR TITLE
GraphQL Subscriptions Support 

### LINKED ISSUE #4: Add support for graphql subscriptions
**Is your feature request related to a problem? Please describe.**

Right now the project supports both synchronous and asynchronous queries against a GraphQL server. One piece of the graphql specification that we don't currently support is creating a connection to a graphql server to read a subscription. If we want to move towards being graphql spec compliant, this is something we should include here.

**Describe the solution you'd like**

I don't have an exact solution in mind here. For the initial version of the feature. We can support a single transport protocol for the subscriptions like web sockets, but in the long run we should look at making it flexible so we can plug in different transport layers without having to change much in the design.

**Describe alternatives you've considered**

No alternatives to the subscriptions from the Graphql spec, but there are a set of alternatives as what the transport protocol looks like for doing the subscriptions. It should be web sockets like https://github.com/apollographql/subscriptions-transport-ws or using server side events like in this node implementation https://github.com/chrisdickinson/sse-stream.

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by DaleSeo**
## What kind of change does this PR introduce?

This PR adds support for GraphQL subscriptions to the client. (fix #4)

## What is the current behavior?

The client only supports GraphQL queries and mutations.

## What is the new behavior?

The client also supports GraphQL subscriptions.

This PR implements the `subscribe` method of the `GraphqlClient` class. The `websockets` dependency is added to the project because GraphQL subscriptions are executed over WebSocket unlike GraphQL queries and mutations.

It wasn't easy to find public APIs that support GraphQL subscriptions. So, I wrote [a very simple API](https://3wqzw.sse.codesandbox.io/) myself for understanding how GraphQL subscriptions work and also for performing some manual testing.

image

The above screenshot is what I captured from the network tab of Chrome Developer Tools after initiating the `messageAdded` subscription. Once the endpoint receives a request in the form of `{"type": "start", "id": "1", "payload": {"query": ..., "variables": ...}}`, it sends back with a series of responses like `{"type": "start", "id": "1", "payload": {"data": ...}}`.

My implementation in this PR is simply based on these behaviors between the client and the server that I observed on the Apollo Playground tool. There must be huge room for improvement but I hope this serves as the first step in enabling the client to support all GraphQL operations.

Here're the manual testing results.

```py
import asyncio
from python_graphql_client import GraphqlClient

client = GraphqlClient(endpoint="wss://3wqzw.sse.codesandbox.io/graphql")

query = """
    subscription onMessageAdded {
        messageAdded
    }
"""

asyncio.run(client.subscribe(query=query, handle=print))
```

```sh
$ python tests/dale.py                                                    
{'data': {'messageAdded': 'Vero autem voluptatem architecto.'}}
{'data': {'messageAdded': 'Est quo sunt est repellendus perspiciatis qui culpa reprehenderit.'}}
{'data': {'messageAdded': 'Inventore nemo quos illo magni voluptates autem quia.'}}
{'data': {'messageAdded': 'Eos omnis minima.'}}
{'data': {'messageAdded': 'Perspiciatis id vitae iure provident omnis assumenda sapiente eum.'}}
{'data': {'messageAdded': 'Dolores autem est.'}}
{'data': {'messageAdded': 'Accusantium temporibus impedit soluta beatae occaecati unde magnam sit.'}}
```

## Does this PR introduce a breaking change?

No. This doesn't touch any of the existing functionalities.

### CODE REVIEW

**Comment by steve148** [comment]
Sorry for being slow with getting a review on this PR, but here's my two cents.

I think the simple implementation you did here is really nice / easy to understand. I'm playing with this locally now to see how the project gets affected by the [different possible message types](https://github.com/graphql-python/graphql-ws/blob/master/graphql_ws/constants.py) and whether or not how this client handles the message makes sense. For example, if the server sends the keep alive type `ka` does our client wait until it receives a proper message with a data payload?

Otherwise once we have a clearer understanding of what the endge cases are for this feature, then I think some more tests to document that would be helpful.

**Comment by steve148** [comment]
I'm going through the [Graphql specification docs](https://github.com/graphql/graphql-spec/blob/master/rfcs/Subscriptions.md) right now as I'm also unsure whether we should be using the python graphql websocket protocol https://github.com/graphql-python/graphql-ws or the apollo graphql websocket protocol https://github.com/apollographql/subscriptions-transport-ws.

**Comment by DaleSeo** [comment]
@steve148 Thanks for your guidance and sorry for the delay in addressing your feedback. I read through the material you shared and had a better understanding of the protocol.

I've added the handshake logic that you mentioned. I've tested it against the demo server you tried and it seems to work properly. It also still works with the test server that I had set up as it did without the handshake logic.

May-09-2020 17-09-25

Below is the code snippet that I used for manual testing for you to try on your own.

```py
import asyncio
from python_graphql_client import GraphqlClient

client = GraphqlClient(endpoint="ws://localhost:4000/subscriptions")

query = """
    subscription {
        messageAdded(channelId: 1) {
            id
            text
        }
    }
"""

asyncio.run(client.subscribe(query=query, handle=print))
```

**Comment by DaleSeo** [comment]
> One note is that it currently does not have a graceful way to handle the graphql server closing a websocket / subscription. Assuming all things work well then this is ok, but in the future we may want to do a better job of alerting the process with a better message for the websocket shutting down.

Totally agreed! We can work on it together down the road. 😎

**Pull request merged**
