### PR TITLE
Release v0.3.2

### PR DESCRIPTION
**Pull request by DaleSeo**
## What kind of change does this PR introduce?

Release

## What is the current behavior?

version 0.3.1

## What is the new behavior?

version 0.3.2

Also updated CHANGELOG.md to reflect the changes we've made so far.

### CODE REVIEW

**Review by steve148 — APPROVED** [review]
🎉

**Comment by steve148** [comment]
@DaleSeo Sorry for the review / removing the review. Should this release count as a patch or as a minor version change?

**Comment by DaleSeo** [comment]
@steve148 On second thought, I'd rather see this as a minor release as it includes API changes though they're unlikely to be breaking changes. Are we on the same page?

**Comment by steve148** [comment]
@DaleSeo we are, this definitely feels like a minor patch, so it should be `0.4.0`.

**Comment by DaleSeo** [comment]
Agreed to release a minor version. Closing in favor of #35

**Pull request closed without merging**
